public with sharing class AddMultipleUnitsController {

  /*  
    public List<WrapperUnitList> EntryList {
        get;
        set;
    }
    public Integer rowToRemove {get;set;}
    
    public AddMultipleUnitsController(){
        EntryList = new List<WrapperUnitList>();
  		addRowToUnitList();
    }
     public void addRowToUnitList(){
     EntryList = AddMultipleUnitsHelper.addNewRowToUnitList(EntryList);
    }
     public void removeRowFromUnitList(){
  EntryList = AddMultipleUnitsHelper.removeRowToUnitList(rowToRemove, EntryList);
   
 }
    
    public PageReference SaveMultiple() {
        system.debug('calling save method');
        AddMultipleUnitsHelper.save(EntryList);
        ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Unit Added Successfully.Thank you!'));
        return null;
    }
    
    
    public class WrapperUnitList{
        public Integer index {get;set;}
        public Unit__c record {get;set;}
   }
    */
}